version: '3.7'

services:
  composer:
    image: composer
    command: composer install
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app

  php:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app

  phpunit:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

  fpm:
    image: php:7.4-fpm
    restart: always
    volumes:
      - .:/app

  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - .conf/nginx/AcmeWidgetCo.conf:/etc/nginx/conf.d/default.conf

  mariadb:
    image: mariadb:10.5.2
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Poland"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "lincolistheman"
      MYSQL_USER: 'grzegorzb'
      MYSQL_PASSWORD: '11235813'
      MYSQL_DATABASE: 'acmecodb'

volumes:
  mariadb-volume:
