version: '3.7'

services:
  composer:
    image: composer
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app

  php:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app

  phpunit:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

  fpm:
    image: php:7.4-fpm
    restart: always
    volumes:
      - .:/app

  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - .conf/nginx/AcmeWidgetCo.conf:/etc/nginx/conf.d/default.conf
